{% set version = "1.1-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-goric
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/goric_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/goric/goric_{{ version }}.tar.gz
  sha256: 40ba2f0fa13f9e0f5dec99d330d255d4b825ccc9e32865c1cd2185cf93e89600

build:
  merge_build_host: true  # [win]
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-mass
    - r-matrix
    - r-mvtnorm
    - r-nlme
    - r-quadprog
  run:
    - r-base
    - r-mass
    - r-matrix
    - r-mvtnorm
    - r-nlme
    - r-quadprog

test:
  commands:
    - $R -e "library('goric')"           # [not win]
    - "\"%R%\" -e \"library('goric')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=goric
  license: GPL-2.0-or-later
  summary: Generalized Order-Restricted Information Criterion (GORIC) value for a set of hypotheses in multivariate linear models and generalised linear models.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: goric
# Type: Package
# Title: Generalized Order-Restricted Information Criterion
# Version: 1.1-0
# Date: 2018-05-30
# Authors@R: c(person("Daniel", "Gerhard", role = c("aut", "cre"), email = "00gerhard@gmail.com"), person("Rebecca M.", "Kuiper", role = "aut"))
# Maintainer: Daniel Gerhard <00gerhard@gmail.com>
# Description: Generalized Order-Restricted Information Criterion (GORIC) value for a set of hypotheses in multivariate linear models and generalised linear models.
# Depends: nlme
# Imports: quadprog, mvtnorm, MASS, Matrix, parallel
# License: GPL (>= 2)
# LazyData: yes
# LazyLoad: yes
# Suggests: knitr
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-05-29 21:37:15 UTC; daniel
# Author: Daniel Gerhard [aut, cre], Rebecca M. Kuiper [aut]
# Repository: CRAN
# Date/Publication: 2018-05-29 22:36:06 UTC
